<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Faker\Factory as Faker;
use App\Models\Product\Product;
use App\Models\Product\ProductImage;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class ProductionProductSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'NVIDIA GeForce RTX 3080 Ti',
                'description' => 'High-end graphics card with Ampere architecture for smooth gaming at 4K resolution.',
                'price' => 1199.99,
                'in_stock' => 1,
                'quantity' => 20,
                'cart_quantity' => 0,
                'category' => 'GPUs',
                'rating' => 4.9,
                'created_at' => now()->subDays(30),
                'updated_at' => now()->subDays(25),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/11152/11152748.png',
                    'title' => 'NVIDIA GeForce RTX 3080 Ti',
                    'description' => 'NVIDIA GeForce RTX 3080 Ti front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'NVIDIA GeForce RTX 3080 Ti front view',
                ]
            ],
            [
                'name' => 'Apple iPad Pro (2022)',
                'description' => 'High-performance tablet with M1 chip, Liquid Retina XDR display, and 5G connectivity.',
                'price' => 1099.00,
                'in_stock' => 1,
                'quantity' => 15,
                'cart_quantity' => 0,
                'category' => 'Phones & Tablets',
                'rating' => 4.8,
                'created_at' => now()->subDays(30),
                'updated_at' => now()->subDays(25),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/4477/4477610.png',
                    'title' => 'Apple iPad Pro (2022)',
                    'description' => 'Apple iPad Pro (2022) front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Apple iPad Pro (2022) front view',
                ]
            ],
            [
                'name' => 'AMD Radeon RX 6700 XT',
                'description' => 'Mid-range graphics card with RDNA 2 architecture for excellent 1440p gaming performance.',
                'price' => 499.99,
                'in_stock' => 1,
                'quantity' => 25,
                'cart_quantity' => 0,
                'category' => 'GPUs',
                'rating' => 4.7,
                'created_at' => now()->subDays(25),
                'updated_at' => now()->subDays(20),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/11152/11152748.png',
                    'title' => 'AMD Radeon RX 6700 XT',
                    'description' => 'AMD Radeon RX 6700 XT front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'AMD Radeon RX 6700 XT front view',
                ]
            ],
            [
                'name' => 'MSI GeForce GTX 1650 SUPER',
                'description' => 'Entry-level graphics card with Turing architecture for budget gaming setups.',
                'price' => 199.99,
                'in_stock' => 1,
                'quantity' => 30,
                'cart_quantity' => 0,
                'category' => 'GPUs',
                'rating' => 4.5,
                'created_at' => now()->subDays(20),
                'updated_at' => now()->subDays(15),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/11152/11152748.png',
                    'title' => 'MSI GeForce GTX 1650 SUPER',
                    'description' => 'MSI GeForce GTX 1650 SUPER front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'MSI GeForce GTX 1650 SUPER front view',
                ]
            ],
            [
                'name' => 'Intel Core i9-11900K',
                'description' => 'Flagship 8-core processor from Intel with high clock speeds for gaming and multitasking.',
                'price' => 549.99,
                'in_stock' => 1,
                'quantity' => 15,
                'cart_quantity' => 0,
                'category' => 'CPUs',
                'rating' => 4.8,
                'created_at' => now()->subDays(15),
                'updated_at' => now()->subDays(10),
                'image' => [
                    'src' => 'https://cdn-icons-png.freepik.com/256/2288/2288010.png',
                    'title' => 'Intel Core i9-11900K',
                    'description' => 'Intel Core i9-11900K top view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Intel Core i9-11900K top view',
                ]
            ],
            [
                'name' => 'AMD Ryzen 5 5600X',
                'description' => '6-core, 12-thread processor from AMD, ideal for gaming and productivity tasks.',
                'price' => 299.99,
                'in_stock' => 1,
                'quantity' => 20,
                'cart_quantity' => 0,
                'category' => 'CPUs',
                'rating' => 4.6,
                'created_at' => now()->subDays(10),
                'updated_at' => now()->subDays(5),
                'image' => [
                    'src' => 'https://cdn-icons-png.freepik.com/256/2288/2288010.png',
                    'title' => 'AMD Ryzen 5 5600X',
                    'description' => 'AMD Ryzen 5 5600X top view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'AMD Ryzen 5 5600X top view',
                ]
            ],
            [
                'name' => 'Asus ROG Strix G15',
                'description' => 'Powerful gaming laptop with AMD Ryzen 9 CPU and NVIDIA GeForce RTX 3070 GPU.',
                'price' => 1799.99,
                'in_stock' => 1,
                'quantity' => 10,
                'cart_quantity' => 0,
                'category' => 'Laptops & PCs',
                'rating' => 4.9,
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(2),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/17014/17014659.png',
                    'title' => 'Asus ROG Strix G15 Gaming Laptop',
                    'description' => 'Asus ROG Strix G15 Gaming Laptop front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Asus ROG Strix G15 Gaming Laptop front view',
                ]
            ],
            [
                'name' => 'Apple iMac 27-inch Retina 5K',
                'description' => 'All-in-one desktop computer with stunning 5K Retina display and powerful Intel Core i9 CPU.',
                'price' => 2299.99,
                'in_stock' => 1,
                'quantity' => 8,
                'cart_quantity' => 0,
                'category' => 'Laptops & PCs',
                'rating' => 4.8,
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDay(),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/17014/17014659.png',
                    'title' => 'Apple iMac 27-inch Retina 5K',
                    'description' => 'Apple iMac 27-inch Retina 5K front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Apple iMac 27-inch Retina 5K front view',
                ]
            ],
            [
                'name' => 'Razer BlackWidow V3 Pro Mechanical Gaming Keyboard',
                'description' => 'Wireless mechanical gaming keyboard with Razer Mechanical Switches and RGB Chroma backlighting.',
                'price' => 229.99,
                'in_stock' => 1,
                'quantity' => 25,
                'cart_quantity' => 0,
                'category' => 'Peripherals',
                'rating' => 4.7,
                'created_at' => now()->subDay(),
                'updated_at' => now(),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/1537/1537589.png',
                    'title' => 'Razer BlackWidow V3 Pro Mechanical Gaming Keyboard',
                    'description' => 'Razer BlackWidow V3 Pro Mechanical Gaming Keyboard front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Razer BlackWidow V3 Pro Mechanical Gaming Keyboard front view',
                ]
            ],
            [
                'name' => 'Logitech G Pro Wireless Gaming Mouse',
                'description' => 'Lightweight wireless gaming mouse with HERO sensor for precise tracking.',
                'price' => 149.99,
                'in_stock' => 1,
                'quantity' => 30,
                'cart_quantity' => 0,
                'category' => 'Peripherals',
                'rating' => 4.8,
                'created_at' => now(),
                'updated_at' => now()->addDay(),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/1537/1537589.png',
                    'title' => 'Logitech G Pro Wireless Gaming Mouse',
                    'description' => 'Logitech G Pro Wireless Gaming Mouse front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Logitech G Pro Wireless Gaming Mouse front view',
                ]
            ],
            [
                'name' => 'ASUS ROG Strix B550-F',
                'description' => 'ATX motherboard with PCIe 4.0 support, optimized for gaming with AMD Ryzen processors.',
                'price' => 199.99,
                'in_stock' => 1,
                'quantity' => 15,
                'cart_quantity' => 0,
                'category' => 'Motherboards',
                'rating' => 4.6,
                'created_at' => now()->addDay(),
                'updated_at' => now()->addDays(2),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/5921/5921800.png',
                    'title' => 'ASUS ROG Strix B550-F Gaming Motherboard',
                    'description' => 'ASUS ROG Strix B550-F Gaming Motherboard top view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'ASUS ROG Strix B550-F Gaming Motherboard top view',
                ]
            ],
            [
                'name' => 'Samsung Galaxy S22 Ultra',
                'description' => 'Flagship smartphone with 6.8" Dynamic AMOLED 2X display, Snapdragon 8 Gen 1 chipset, and 108MP camera.',
                'price' => 1199.99,
                'in_stock' => 1,
                'quantity' => 20,
                'cart_quantity' => 0,
                'category' => 'Phones & Tablets',
                'rating' => 4.9,
                'created_at' => now()->subDays(35),
                'updated_at' => now()->subDays(30),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/4477/4477610.png',
                    'title' => 'Samsung Galaxy S22 Ultra',
                    'description' => 'Samsung Galaxy S22 Ultra front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Samsung Galaxy S22 Ultra front view',
                ]
            ],
            [
                'name' => 'GIGABYTE Z590 AORUS PRO AX',
                'description' => 'High-performance motherboard with Intel Z590 chipset, ideal for gaming and overclocking.',
                'price' => 279.99,
                'in_stock' => 1,
                'quantity' => 12,
                'cart_quantity' => 0,
                'category' => 'Motherboards',
                'rating' => 4.7,
                'created_at' => now()->addDays(2),
                'updated_at' => now()->addDays(4),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/5921/5921800.png',
                    'title' => 'GIGABYTE Z590 AORUS PRO AX',
                    'description' => 'GIGABYTE Z590 AORUS PRO AX top view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'GIGABYTE Z590 AORUS PRO AX top view',
                ]
            ],
            [
                'name' => 'NZXT H510 Elite ATX Mid Tower Case',
                'description' => 'Stylish ATX Mid Tower case with tempered glass side panel and RGB lighting.',
                'price' => 149.99,
                'in_stock' => 1,
                'quantity' => 18,
                'cart_quantity' => 0,
                'category' => 'Computer Cases',
                'rating' => 4.8,
                'created_at' => now()->addDays(4),
                'updated_at' => now()->addDays(6),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/11152/11152835.png',
                    'title' => 'NZXT H510 Elite ATX Mid Tower Case',
                    'description' => 'NZXT H510 Elite ATX Mid Tower Case front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'NZXT H510 Elite ATX Mid Tower Case front view',
                ]
            ],
            [
                'name' => 'Google Pixel 6 Pro',
                'description' => 'Premium Android smartphone with 6.7" OLED display, Google Tensor chip, and 50MP main camera.',
                'price' => 899.00,
                'in_stock' => 1,
                'quantity' => 18,
                'cart_quantity' => 0,
                'category' => 'Phones & Tablets',
                'rating' => 4.7,
                'created_at' => now()->subDays(40),
                'updated_at' => now()->subDays(35),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/4477/4477610.png',
                    'title' => 'Google Pixel 6 Pro',
                    'description' => 'Google Pixel 6 Pro front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Google Pixel 6 Pro front view',
                ]
            ],
            [
                'name' => 'Corsair Crystal 680X RGB ATX Mid Tower Case',
                'description' => 'Premium ATX Mid Tower case with dual-chamber layout and three RGB fans for superior airflow.',
                'price' => 249.99,
                'in_stock' => 1,
                'quantity' => 22,
                'cart_quantity' => 0,
                'category' => 'Computer Cases',
                'rating' => 4.9,
                'created_at' => now()->addDays(6),
                'updated_at' => now()->addDays(8),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/11152/11152835.png',
                    'title' => 'Corsair Crystal 680X RGB ATX Mid Tower Case',
                    'description' => 'Corsair Crystal 680X RGB ATX Mid Tower Case front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Corsair Crystal 680X RGB ATX Mid Tower Case front view',
                ]
            ],
            [
                'name' => 'AMD Radeon RX 6800 XT',
                'description' => 'High-performance graphics card with RDNA 2 architecture for 4K gaming and content creation.',
                'price' => 649.99,
                'in_stock' => 1,
                'quantity' => 15,
                'cart_quantity' => 0,
                'category' => 'GPUs',
                'rating' => 4.8,
                'created_at' => now()->subDays(10),
                'updated_at' => now()->subDays(5),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/11152/11152748.png',
                    'title' => 'AMD Radeon RX 6800 XT',
                    'description' => 'AMD Radeon RX 6800 XT front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'AMD Radeon RX 6800 XT front view',
                ]
            ],
            [
                'name' => 'Apple iPhone SE (2022)',
                'description' => 'Compact iPhone with A15 Bionic chip, 4.7" Retina HD display, and 5G support.',
                'price' => 499.00,
                'in_stock' => 1,
                'quantity' => 16,
                'cart_quantity' => 0,
                'category' => 'Phones & Tablets',
                'rating' => 4.6,
                'created_at' => now()->subDays(45),
                'updated_at' => now()->subDays(40),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/4477/4477610.png',
                    'title' => 'Apple iPhone SE (2022)',
                    'description' => 'Apple iPhone SE (2022) front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Apple iPhone SE (2022) front view',
                ]
            ],
            [
                'name' => 'NVIDIA GeForce GTX 1660 Super',
                'description' => 'Budget-friendly graphics card with Turing architecture for smooth 1080p gaming.',
                'price' => 299.99,
                'in_stock' => 1,
                'quantity' => 20,
                'cart_quantity' => 0,
                'category' => 'GPUs',
                'rating' => 4.5,
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(2),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/11152/11152748.png',
                    'title' => 'NVIDIA GeForce GTX 1660 Super',
                    'description' => 'NVIDIA GeForce GTX 1660 Super front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'NVIDIA GeForce GTX 1660 Super front view',
                ]
            ],
            [
                'name' => 'Intel Core i7-11700K',
                'description' => '8-core processor from Intel with high clock speeds for gaming and multitasking.',
                'price' => 399.99,
                'in_stock' => 1,
                'quantity' => 18,
                'cart_quantity' => 0,
                'category' => 'CPUs',
                'rating' => 4.7,
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDay(),
                'image' => [
                    'src' => 'https://cdn-icons-png.freepik.com/256/2288/2288010.png',
                    'title' => 'Intel Core i7-11700K',
                    'description' => 'Intel Core i7-11700K top view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Intel Core i7-11700K top view',
                ]
            ],
            [
                'name' => 'AMD Ryzen 7 5800X',
                'description' => '8-core, 16-thread processor from AMD, excellent for gaming and productivity tasks.',
                'price' => 449.99,
                'in_stock' => 1,
                'quantity' => 17,
                'cart_quantity' => 0,
                'category' => 'CPUs',
                'rating' => 4.9,
                'created_at' => now()->subDay(),
                'updated_at' => now()->addDay(),
                'image' => [
                    'src' => 'https://cdn-icons-png.freepik.com/256/2288/2288010.png',
                    'title' => 'AMD Ryzen 7 5800X',
                    'description' => 'AMD Ryzen 7 5800X top view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'AMD Ryzen 7 5800X top view',
                ]
            ],
            [
                'name' => 'Samsung Galaxy Tab S8+',
                'description' => 'Large Android tablet with 12.4" Super AMOLED display, Snapdragon 8 Gen 1 chipset, and S Pen support.',
                'price' => 999.99,
                'in_stock' => 1,
                'quantity' => 14,
                'cart_quantity' => 0,
                'category' => 'Phones & Tablets',
                'rating' => 4.8,
                'created_at' => now()->subDays(50),
                'updated_at' => now()->subDays(45),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/4477/4477610.png',
                    'title' => 'Samsung Galaxy Tab S8+',
                    'description' => 'Samsung Galaxy Tab S8+ front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Samsung Galaxy Tab S8+ front view',
                ]
            ],
            [
                'name' => 'HP Pavilion Gaming Desktop',
                'description' => 'Entry-level gaming desktop with AMD Ryzen 5 CPU and NVIDIA GeForce GTX 1650 GPU.',
                'price' => 899.99,
                'in_stock' => 1,
                'quantity' => 12,
                'cart_quantity' => 0,
                'category' => 'Laptops & PCs',
                'rating' => 4.6,
                'created_at' => now()->addDay(),
                'updated_at' => now()->addDays(2),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/17014/17014659.png',
                    'title' => 'HP Pavilion Gaming Desktop',
                    'description' => 'HP Pavilion Gaming Desktop front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'HP Pavilion Gaming Desktop front view',
                ]
            ],
            [
                'name' => 'Dell Alienware m15 R6',
                'description' => 'Thin and powerful gaming laptop with Intel Core i7 CPU and NVIDIA GeForce RTX 3060 GPU.',
                'price' => 1699.99,
                'in_stock' => 1,
                'quantity' => 10,
                'cart_quantity' => 0,
                'category' => 'Laptops & PCs',
                'rating' => 4.8,
                'created_at' => now()->addDays(2),
                'updated_at' => now()->addDays(4),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/17014/17014659.png',
                    'title' => 'Dell Alienware m15 R6 Gaming Laptop',
                    'description' => 'Dell Alienware m15 R6 Gaming Laptop front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Dell Alienware m15 R6 Gaming Laptop front view',
                ]
            ],
            [
                'name' => 'SteelSeries Apex Pro TKL Mechanical Gaming Keyboard',
                'description' => 'Premium mechanical gaming keyboard with adjustable OmniPoint switches and OLED Smart Display.',
                'price' => 199.99,
                'in_stock' => 1,
                'quantity' => 22,
                'cart_quantity' => 0,
                'category' => 'Peripherals',
                'rating' => 4.9,
                'created_at' => now()->addDays(4),
                'updated_at' => now()->addDays(6),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/1537/1537589.png',
                    'title' => 'SteelSeries Apex Pro TKL Mechanical Gaming Keyboard',
                    'description' => 'SteelSeries Apex Pro TKL Mechanical Gaming Keyboard front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'SteelSeries Apex Pro TKL Mechanical Gaming Keyboard front view',
                ]
            ],
            [
                'name' => 'Corsair Dark Core RGB SE Wireless Gaming Mouse',
                'description' => 'Wireless gaming mouse with customizable RGB lighting and Qi wireless charging support.',
                'price' => 89.99,
                'in_stock' => 1,
                'quantity' => 25,
                'cart_quantity' => 0,
                'category' => 'Peripherals',
                'rating' => 4.7,
                'created_at' => now()->addDays(6),
                'updated_at' => now()->addDays(8),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/1537/1537589.png',
                    'title' => 'Corsair Dark Core RGB SE Wireless Gaming Mouse',
                    'description' => 'Corsair Dark Core RGB SE Wireless Gaming Mouse front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Corsair Dark Core RGB SE Wireless Gaming Mouse front view',
                ]
            ],
            [
                'name' => 'ASRock B550M Pro4 Micro ATX Motherboard',
                'description' => 'Micro ATX motherboard with PCIe 4.0 support, ideal for compact gaming builds.',
                'price' => 129.99,
                'in_stock' => 1,
                'quantity' => 18,
                'cart_quantity' => 0,
                'category' => 'Motherboards',
                'rating' => 4.6,
                'created_at' => now()->addDays(8),
                'updated_at' => now()->addDays(10),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/5921/5921800.png',
                    'title' => 'ASRock B550M Pro4 Micro ATX Motherboard',
                    'description' => 'ASRock B550M Pro4 Micro ATX Motherboard top view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'ASRock B550M Pro4 Micro ATX Motherboard top view',
                ]
            ],
            [
                'name' => 'MSI MAG B550 Tomahawk ATX Motherboard',
                'description' => 'ATX motherboard with PCIe 4.0, Mystic Light RGB lighting, and robust thermal solution.',
                'price' => 179.99,
                'in_stock' => 1,
                'quantity' => 16,
                'cart_quantity' => 0,
                'category' => 'Motherboards',
                'rating' => 4.7,
                'created_at' => now()->addDays(10),
                'updated_at' => now()->addDays(12),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/5921/5921800.png',
                    'title' => 'MSI MAG B550 Tomahawk ATX Motherboard',
                    'description' => 'MSI MAG B550 Tomahawk ATX Motherboard top view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'MSI MAG B550 Tomahawk ATX Motherboard top view',
                ]
            ],
            [
                'name' => 'Google Pixel 5a',
                'description' => 'Affordable Google Pixel smartphone with 6.34" OLED display, Snapdragon 765G chipset, and dual-camera system.',
                'price' => 449.00,
                'in_stock' => 1,
                'quantity' => 16,
                'cart_quantity' => 0,
                'category' => 'Phones & Tablets',
                'rating' => 4.5,
                'created_at' => now()->subDays(100),
                'updated_at' => now()->subDays(95),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/4477/4477610.png',
                    'title' => 'Google Pixel 5a',
                    'description' => 'Google Pixel 5a front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Google Pixel 5a front view',
                ]
            ],
            [
                'name' => 'Fractal Design Meshify C ATX Mid Tower Case',
                'description' => 'ATX Mid Tower case with high airflow design and tempered glass side panel.',
                'price' => 109.99,
                'in_stock' => 1,
                'quantity' => 20,
                'cart_quantity' => 0,
                'category' => 'Computer Cases',
                'rating' => 4.8,
                'created_at' => now()->addDays(12),
                'updated_at' => now()->addDays(14),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/11152/11152835.png',
                    'title' => 'Fractal Design Meshify C ATX Mid Tower Case',
                    'description' => 'Fractal Design Meshify C ATX Mid Tower Case front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Fractal Design Meshify C ATX Mid Tower Case front view',
                ]
            ],
            [
                'name' => 'NZXT H710i ATX Mid Tower Case',
                'description' => 'Premium ATX Mid Tower case with integrated RGB lighting and advanced cable management.',
                'price' => 179.99,
                'in_stock' => 1,
                'quantity' => 18,
                'cart_quantity' => 0,
                'category' => 'Computer Cases',
                'rating' => 4.9,
                'created_at' => now()->addDays(14),
                'updated_at' => now()->addDays(16),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/11152/11152835.png',
                    'title' => 'NZXT H710i ATX Mid Tower Case',
                    'description' => 'NZXT H710i ATX Mid Tower Case front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'NZXT H710i ATX Mid Tower Case front view',
                ]
            ],
            [
                'name' => 'ASUS ROG Strix GeForce RTX 3070',
                'description' => 'Powerful graphics card with Ampere architecture for high-performance gaming and VR experiences.',
                'price' => 899.99,
                'in_stock' => 1,
                'quantity' => 12,
                'cart_quantity' => 0,
                'category' => 'GPUs',
                'rating' => 4.8,
                'created_at' => now()->subDays(10),
                'updated_at' => now()->subDays(5),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/11152/11152748.png',
                    'title' => 'ASUS ROG Strix GeForce RTX 3070',
                    'description' => 'ASUS ROG Strix GeForce RTX 3070 front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'ASUS ROG Strix GeForce RTX 3070 front view',
                ]
            ],
            [
                'name' => 'MSI GeForce GTX 1650 Super Ventus XS OC',
                'description' => 'Affordable graphics card with Turing architecture for smooth 1080p gaming.',
                'price' => 229.99,
                'in_stock' => 1,
                'quantity' => 18,
                'cart_quantity' => 0,
                'category' => 'GPUs',
                'rating' => 4.5,
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(2),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/11152/11152748.png',
                    'title' => 'MSI GeForce GTX 1650 Super Ventus XS OC',
                    'description' => 'MSI GeForce GTX 1650 Super Ventus XS OC front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'MSI GeForce GTX 1650 Super Ventus XS OC front view',
                ]
            ],
            [
                'name' => 'AMD Ryzen 5 5600X',
                'description' => '6-core, 12-thread processor from AMD, ideal for gaming and productivity.',
                'price' => 299.99,
                'in_stock' => 1,
                'quantity' => 20,
                'cart_quantity' => 0,
                'category' => 'CPUs',
                'rating' => 4.7,
                'created_at' => now()->subDays(10),
                'updated_at' => now()->subDays(5),
                'image' => [
                    'src' => 'https://cdn-icons-png.freepik.com/256/2288/2288010.png',
                    'title' => 'AMD Ryzen 5 5600X',
                    'description' => 'AMD Ryzen 5 5600X top view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'AMD Ryzen 5 5600X top view',
                ]
            ],
            [
                'name' => 'Intel Core i5-11600K',
                'description' => '6-core, 12-thread processor from Intel, offering excellent performance for gaming and everyday tasks.',
                'price' => 269.99,
                'in_stock' => 1,
                'quantity' => 22,
                'cart_quantity' => 0,
                'category' => 'CPUs',
                'rating' => 4.6,
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDay(),
                'image' => [
                    'src' => 'https://cdn-icons-png.freepik.com/256/2288/2288010.png',
                    'title' => 'Intel Core i5-11600K',
                    'description' => 'Intel Core i5-11600K top view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Intel Core i5-11600K top view',
                ]
            ],
            [
                'name' => 'Acer Nitro 5',
                'description' => 'Budget-friendly gaming laptop with AMD Ryzen 7 CPU and NVIDIA GeForce GTX 1650 GPU.',
                'price' => 799.99,
                'in_stock' => 1,
                'quantity' => 15,
                'cart_quantity' => 0,
                'category' => 'Laptops & PCs',
                'rating' => 4.4,
                'created_at' => now()->subDays(10),
                'updated_at' => now()->subDays(5),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/17014/17014659.png',
                    'title' => 'Acer Nitro 5 Gaming Laptop',
                    'description' => 'Acer Nitro 5 Gaming Laptop front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Acer Nitro 5 Gaming Laptop front view',
                ]
            ],
            [
                'name' => 'Apple MacBook Air M1',
                'description' => 'Thin and light MacBook with Apple Silicon M1 chip for fast performance and long battery life.',
                'price' => 999.99,
                'in_stock' => 1,
                'quantity' => 18,
                'cart_quantity' => 0,
                'category' => 'Laptops & PCs',
                'rating' => 4.8,
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDay(),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/17014/17014659.png',
                    'title' => 'Apple MacBook Air M1',
                    'description' => 'Apple MacBook Air M1 top view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Apple MacBook Air M1 top view',
                ]
            ],
            [
                'name' => 'Razer DeathAdder V2 Gaming Mouse',
                'description' => 'Ergonomic gaming mouse with Razer Optical Mouse Switches and 20K DPI optical sensor.',
                'price' => 69.99,
                'in_stock' => 1,
                'quantity' => 20,
                'cart_quantity' => 0,
                'category' => 'Peripherals',
                'rating' => 4.7,
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDay(),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/1537/1537589.png',
                    'title' => 'Razer DeathAdder V2 Gaming Mouse',
                    'description' => 'Razer DeathAdder V2 Gaming Mouse front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Razer DeathAdder V2 Gaming Mouse front view',
                ]
            ],
            [
                'name' => 'Logitech G Pro X Superlight Wireless Gaming Mouse',
                'description' => 'Ultra-lightweight wireless gaming mouse with HERO sensor and long battery life.',
                'price' => 149.99,
                'in_stock' => 1,
                'quantity' => 18,
                'cart_quantity' => 0,
                'category' => 'Peripherals',
                'rating' => 4.9,
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDay(),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/1537/1537589.png',
                    'title' => 'Logitech G Pro X Superlight Wireless Gaming Mouse',
                    'description' => 'Logitech G Pro X Superlight Wireless Gaming Mouse front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Logitech G Pro X Superlight Wireless Gaming Mouse front view',
                ]
            ],
            [
                'name' => 'Sony Xperia 10 III',
                'description' => 'Mid-range Xperia smartphone with 6" OLED display, Snapdragon 690 chipset, and triple-camera system.',
                'price' => 499.00,
                'in_stock' => 1,
                'quantity' => 20,
                'cart_quantity' => 0,
                'category' => 'Phones & Tablets',
                'rating' => 4.6,
                'created_at' => now()->subDays(95),
                'updated_at' => now()->subDays(90),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/4477/4477610.png',
                    'title' => 'Sony Xperia 10 III',
                    'description' => 'Sony Xperia 10 III front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Sony Xperia 10 III front view',
                ]
            ],
            [
                'name' => 'GIGABYTE Z590 AORUS ELITE AX ATX Motherboard',
                'description' => 'ATX motherboard with PCIe 4.0 support, WiFi 6, and RGB Fusion 2.0 for gaming enthusiasts.',
                'price' => 229.99,
                'in_stock' => 1,
                'quantity' => 16,
                'cart_quantity' => 0,
                'category' => 'Motherboards',
                'rating' => 4.7,
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDay(),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/5921/5921800.png',
                    'title' => 'GIGABYTE Z590 AORUS ELITE AX ATX Motherboard',
                    'description' => 'GIGABYTE Z590 AORUS ELITE AX ATX Motherboard top view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'GIGABYTE Z590 AORUS ELITE AX ATX Motherboard top view',
                ]
            ],
            [
                'name' => 'ASUS ROG Crosshair VIII Hero X570 ATX Motherboard',
                'description' => 'High-end ATX motherboard with AMD X570 chipset, Aura Sync RGB lighting, and robust power delivery.',
                'price' => 379.99,
                'in_stock' => 1,
                'quantity' => 14,
                'cart_quantity' => 0,
                'category' => 'Motherboards',
                'rating' => 4.8,
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subDay(),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/5921/5921800.png',
                    'title' => 'ASUS ROG Crosshair VIII Hero X570 ATX Motherboard',
                    'description' => 'ASUS ROG Crosshair VIII Hero X570 ATX Motherboard top view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'ASUS ROG Crosshair VIII Hero X570 ATX Motherboard top view',
                ]
            ],
            [
                'name' => 'Corsair iCUE 5000X RGB ATX Mid Tower Case',
                'description' => 'Mid Tower case with tempered glass side panel and RGB lighting control via iCUE software.',
                'price' => 189.99,
                'in_stock' => 1,
                'quantity' => 20,
                'cart_quantity' => 0,
                'category' => 'Computer Cases',
                'rating' => 4.8,
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subDay(),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/11152/11152835.png',
                    'title' => 'Corsair iCUE 5000X RGB ATX Mid Tower Case',
                    'description' => 'Corsair iCUE 5000X RGB ATX Mid Tower Case front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Corsair iCUE 5000X RGB ATX Mid Tower Case front view',
                ]
            ],
            [
                'name' => 'NZXT H510 Elite ATX Mid Tower Case',
                'description' => 'Premium Mid Tower case with tempered glass front and side panels, and integrated RGB lighting.',
                'price' => 169.99,
                'in_stock' => 1,
                'quantity' => 18,
                'cart_quantity' => 0,
                'category' => 'Computer Cases',
                'rating' => 4.9,
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDay(),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/11152/11152835.png',
                    'title' => 'NZXT H510 Elite ATX Mid Tower Case',
                    'description' => 'NZXT H510 Elite ATX Mid Tower Case front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'NZXT H510 Elite ATX Mid Tower Case front view',
                ]
            ],
            [
                'name' => 'EVGA GeForce RTX 3060 Ti FTW3 Ultra Gaming',
                'description' => 'High-performance graphics card with RTX 3060 Ti chipset, ideal for gaming at 1440p resolution.',
                'price' => 499.99,
                'in_stock' => 1,
                'quantity' => 15,
                'cart_quantity' => 0,
                'category' => 'GPUs',
                'rating' => 4.7,
                'created_at' => now()->subDays(7),
                'updated_at' => now()->subDays(2),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/11152/11152748.png',
                    'title' => 'EVGA GeForce RTX 3060 Ti FTW3 Ultra Gaming',
                    'description' => 'EVGA GeForce RTX 3060 Ti FTW3 Ultra Gaming front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'EVGA GeForce RTX 3060 Ti FTW3 Ultra Gaming front view',
                ]
            ],
            [
                'name' => 'MSI Radeon RX 6900 XT Gaming X Trio',
                'description' => 'Flagship AMD Radeon RX 6900 XT graphics card with high performance and efficient cooling.',
                'price' => 1499.99,
                'in_stock' => 1,
                'quantity' => 8,
                'cart_quantity' => 0,
                'category' => 'GPUs',
                'rating' => 4.9,
                'created_at' => now()->subDays(10),
                'updated_at' => now()->subDays(5),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/11152/11152748.png',
                    'title' => 'MSI Radeon RX 6900 XT Gaming X Trio',
                    'description' => 'MSI Radeon RX 6900 XT Gaming X Trio front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'MSI Radeon RX 6900 XT Gaming X Trio front view',
                ]
            ],
            [
                'name' => 'AMD Ryzen 9 5900X',
                'description' => '12-core, 24-thread processor from AMD Ryzen 5000 series, designed for high-end gaming and productivity.',
                'price' => 549.99,
                'in_stock' => 1,
                'quantity' => 12,
                'cart_quantity' => 0,
                'category' => 'CPUs',
                'rating' => 4.9,
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDay(),
                'image' => [
                    'src' => 'https://cdn-icons-png.freepik.com/256/2288/2288010.png',
                    'title' => 'AMD Ryzen 9 5900X',
                    'description' => 'AMD Ryzen 9 5900X top view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'AMD Ryzen 9 5900X top view',
                ]
            ],
            [
                'name' => 'Intel Core i7-11700K',
                'description' => '8-core, 16-thread processor from Intel, offering strong performance for gaming and multitasking.',
                'price' => 399.99,
                'in_stock' => 1,
                'quantity' => 14,
                'cart_quantity' => 0,
                'category' => 'CPUs',
                'rating' => 4.8,
                'created_at' => now()->subDays(7),
                'updated_at' => now()->subDays(2),
                'image' => [
                    'src' => 'https://cdn-icons-png.freepik.com/256/2288/2288010.png',
                    'title' => 'Intel Core i7-11700K',
                    'description' => 'Intel Core i7-11700K top view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Intel Core i7-11700K top view',
                ]
            ],
            [
                'name' => 'HP Pavilion Gaming Desktop',
                'description' => 'Affordable gaming desktop with AMD Ryzen 5 CPU and NVIDIA GeForce GTX 1650 GPU, perfect for entry-level gamers.',
                'price' => 899.99,
                'in_stock' => 1,
                'quantity' => 16,
                'cart_quantity' => 0,
                'category' => 'Laptops & PCs',
                'rating' => 4.5,
                'created_at' => now()->subDays(7),
                'updated_at' => now()->subDays(2),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/17014/17014659.png',
                    'title' => 'HP Pavilion Gaming Desktop',
                    'description' => 'HP Pavilion Gaming Desktop front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'HP Pavilion Gaming Desktop front view',
                ]
            ],
            [
                'name' => 'Dell Inspiron 15 7000 Series Laptop',
                'description' => '15.6-inch laptop with Intel Core i7 CPU, NVIDIA GeForce GTX 1650 GPU, and Full HD display, ideal for work and light gaming.',
                'price' => 1199.99,
                'in_stock' => 1,
                'quantity' => 18,
                'cart_quantity' => 0,
                'category' => 'Laptops & PCs',
                'rating' => 4.7,
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDay(),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/17014/17014659.png',
                    'title' => 'Dell Inspiron 15 7000 Series Laptop',
                    'description' => 'Dell Inspiron 15 7000 Series Laptop front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Dell Inspiron 15 7000 Series Laptop front view',
                ]
            ],
            [
                'name' => 'SteelSeries Apex Pro TKL Mechanical Gaming Keyboard',
                'description' => 'Compact mechanical gaming keyboard with adjustable OmniPoint switches for customizable actuation points.',
                'price' => 179.99,
                'in_stock' => 1,
                'quantity' => 20,
                'cart_quantity' => 0,
                'category' => 'Peripherals',
                'rating' => 4.8,
                'created_at' => now()->subDays(7),
                'updated_at' => now()->subDays(2),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/1537/1537589.png',
                    'title' => 'SteelSeries Apex Pro TKL Mechanical Gaming Keyboard',
                    'description' => 'SteelSeries Apex Pro TKL Mechanical Gaming Keyboard front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'SteelSeries Apex Pro TKL Mechanical Gaming Keyboard front view',
                ]
            ],
            [
                'name' => 'Corsair K70 RGB MK.2 Mechanical Gaming Keyboard',
                'description' => 'Mechanical gaming keyboard with Cherry MX switches and per-key RGB backlighting, designed for gaming enthusiasts.',
                'price' => 159.99,
                'in_stock' => 1,
                'quantity' => 22,
                'cart_quantity' => 0,
                'category' => 'Peripherals',
                'rating' => 4.7,
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDay(),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/1537/1537589.png',
                    'title' => 'Corsair K70 RGB MK.2 Mechanical Gaming Keyboard',
                    'description' => 'Corsair K70 RGB MK.2 Mechanical Gaming Keyboard front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Corsair K70 RGB MK.2 Mechanical Gaming Keyboard front view',
                ]
            ],
            [
                'name' => 'ASUS ROG Maximus XIII Hero Z590 ATX Motherboard',
                'description' => 'High-end ATX motherboard with Intel Z590 chipset, robust power delivery, and extensive connectivity options for gaming.',
                'price' => 499.99,
                'in_stock' => 1,
                'quantity' => 14,
                'cart_quantity' => 0,
                'category' => 'Motherboards',
                'rating' => 4.9,
                'created_at' => now()->subDays(7),
                'updated_at' => now()->subDays(2),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/5921/5921800.png',
                    'title' => 'ASUS ROG Maximus XIII Hero Z590 ATX Motherboard',
                    'description' => 'ASUS ROG Maximus XIII Hero Z590 ATX Motherboard top view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'ASUS ROG Maximus XIII Hero Z590 ATX Motherboard top view',
                ]
            ],
            [
                'name' => 'MSI MAG B550 Tomahawk ATX Motherboard',
                'description' => 'ATX motherboard with AMD B550 chipset, Mystic Light RGB lighting, and support for AMD Ryzen processors.',
                'price' => 179.99,
                'in_stock' => 1,
                'quantity' => 16,
                'cart_quantity' => 0,
                'category' => 'Motherboards',
                'rating' => 4.7,
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDay(),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/5921/5921800.png',
                    'title' => 'MSI MAG B550 Tomahawk ATX Motherboard',
                    'description' => 'MSI MAG B550 Tomahawk ATX Motherboard top view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'MSI MAG B550 Tomahawk ATX Motherboard top view',
                ]
            ],
            [
                'name' => 'NZXT H710i ATX Mid Tower Case',
                'description' => 'Mid Tower case with integrated RGB lighting and tempered glass side panel, optimized for cooling and cable management.',
                'price' => 179.99,
                'in_stock' => 1,
                'quantity' => 18,
                'cart_quantity' => 0,
                'category' => 'Computer Cases',
                'rating' => 4.8,
                'created_at' => now()->subDays(7),
                'updated_at' => now()->subDays(2),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/11152/11152835.png',
                    'title' => 'NZXT H710i ATX Mid Tower Case',
                    'description' => 'NZXT H710i ATX Mid Tower Case front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'NZXT H710i ATX Mid Tower Case front view',
                ]
            ],
            [
                'name' => 'Phanteks Eclipse P500A ATX Mid Tower Case',
                'description' => 'High airflow Mid Tower case with tempered glass side panel, optimized for cooling performance with spacious interior.',
                'price' => 139.99,
                'in_stock' => 1,
                'quantity' => 20,
                'cart_quantity' => 0,
                'category' => 'Computer Cases',
                'rating' => 4.7,
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDay(),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/11152/11152835.png',
                    'title' => 'Phanteks Eclipse P500A ATX Mid Tower Case',
                    'description' => 'Phanteks Eclipse P500A ATX Mid Tower Case front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Phanteks Eclipse P500A ATX Mid Tower Case front view',
                ]
            ],
            [
                'name' => 'NVIDIA GeForce RTX 3090 Founders Edition',
                'description' => 'Flagship graphics card from NVIDIA, featuring 24GB GDDR6X VRAM and exceptional gaming performance.',
                'price' => 1499.99,
                'in_stock' => 1,
                'quantity' => 10,
                'cart_quantity' => 0,
                'category' => 'GPUs',
                'rating' => 4.9,
                'created_at' => now()->subDays(10),
                'updated_at' => now()->subDays(5),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/11152/11152748.png',
                    'title' => 'NVIDIA GeForce RTX 3090 Founders Edition',
                    'description' => 'NVIDIA GeForce RTX 3090 Founders Edition front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'NVIDIA GeForce RTX 3090 Founders Edition front view',
                ]
            ],
            [
                'name' => 'AMD Ryzen 7 5800X',
                'description' => '8-core, 16-thread processor from AMD Ryzen 5000 series, designed for high-end gaming and multitasking.',
                'price' => 449.99,
                'in_stock' => 1,
                'quantity' => 15,
                'cart_quantity' => 0,
                'category' => 'CPUs',
                'rating' => 4.8,
                'created_at' => now()->subDays(8),
                'updated_at' => now()->subDays(3),
                'image' => [
                    'src' => 'https://cdn-icons-png.freepik.com/256/2288/2288010.png',
                    'title' => 'AMD Ryzen 7 5800X',
                    'description' => 'AMD Ryzen 7 5800X top view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'AMD Ryzen 7 5800X top view',
                ]
            ],
            [
                'name' => 'Alienware Aurora R12 Gaming Desktop',
                'description' => 'High-performance gaming desktop with Intel Core i9 CPU, NVIDIA GeForce RTX 3080 GPU, and advanced cooling system.',
                'price' => 2399.99,
                'in_stock' => 1,
                'quantity' => 12,
                'cart_quantity' => 0,
                'category' => 'Laptops & PCs',
                'rating' => 4.7,
                'created_at' => now()->subDays(6),
                'updated_at' => now()->subDay(),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/17014/17014659.png',
                    'title' => 'Alienware Aurora R12 Gaming Desktop',
                    'description' => 'Alienware Aurora R12 Gaming Desktop front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Alienware Aurora R12 Gaming Desktop front view',
                ]
            ],
            [
                'name' => 'Logitech G502 HERO Gaming Mouse',
                'description' => 'High-performance gaming mouse with HERO sensor for precise tracking and customizable weights and RGB lighting.',
                'price' => 79.99,
                'in_stock' => 1,
                'quantity' => 18,
                'cart_quantity' => 0,
                'category' => 'Peripherals',
                'rating' => 4.6,
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDay(),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/1537/1537589.png',
                    'title' => 'Logitech G502 HERO Gaming Mouse',
                    'description' => 'Logitech G502 HERO Gaming Mouse front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Logitech G502 HERO Gaming Mouse front view',
                ]
            ],
            [
                'name' => 'ASUS ROG Crosshair VIII Hero ATX Motherboard',
                'description' => 'High-end ATX motherboard with AMD X570 chipset, ROG SupremeFX audio, and Aura Sync RGB lighting.',
                'price' => 379.99,
                'in_stock' => 1,
                'quantity' => 20,
                'cart_quantity' => 0,
                'category' => 'Motherboards',
                'rating' => 4.8,
                'created_at' => now()->subDays(4),
                'updated_at' => now()->subDays(1),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/5921/5921800.png',
                    'title' => 'ASUS ROG Crosshair VIII Hero ATX Motherboard',
                    'description' => 'ASUS ROG Crosshair VIII Hero ATX Motherboard top view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'ASUS ROG Crosshair VIII Hero ATX Motherboard top view',
                ]
            ],
            [
                'name' => 'NZXT H510 Elite Compact ATX Mid Tower Case',
                'description' => 'Compact Mid Tower case with tempered glass front and side panels, and pre-installed RGB lighting.',
                'price' => 149.99,
                'in_stock' => 1,
                'quantity' => 16,
                'cart_quantity' => 0,
                'category' => 'Computer Cases',
                'rating' => 4.7,
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subDay(),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/11152/11152835.png',
                    'title' => 'NZXT H510 Elite Compact ATX Mid Tower Case',
                    'description' => 'NZXT H510 Elite Compact ATX Mid Tower Case front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'NZXT H510 Elite Compact ATX Mid Tower Case front view',
                ]
            ],
            [
                'name' => 'Gigabyte GeForce GTX 1660 SUPER OC 6G',
                'description' => 'Mid-range graphics card with GeForce GTX 1660 SUPER chipset, ideal for 1080p gaming and content creation.',
                'price' => 299.99,
                'in_stock' => 0,
                'quantity' => 0,
                'cart_quantity' => 0,
                'category' => 'GPUs',
                'rating' => 4.5,
                'created_at' => now()->subDays(10),
                'updated_at' => now()->subDays(5),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/11152/11152748.png',
                    'title' => 'Gigabyte GeForce GTX 1660 SUPER OC 6G',
                    'description' => 'Gigabyte GeForce GTX 1660 SUPER OC 6G front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Gigabyte GeForce GTX 1660 SUPER OC 6G front view',
                ]
            ],
            [
                'name' => 'Intel Core i5-11600K',
                'description' => '6-core, 12-thread processor from Intel Core 11th Gen, offering excellent gaming and multitasking performance.',
                'price' => 279.99,
                'in_stock' => 0,
                'quantity' => 0,
                'cart_quantity' => 0,
                'category' => 'CPUs',
                'rating' => 4.6,
                'created_at' => now()->subDays(8),
                'updated_at' => now()->subDays(3),
                'image' => [
                    'src' => 'https://cdn-icons-png.freepik.com/256/2288/2288010.png',
                    'title' => 'Intel Core i5-11600K',
                    'description' => 'Intel Core i5-11600K top view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Intel Core i5-11600K top view',
                ]
            ],
            [
                'name' => 'Lenovo Legion 5 Pro',
                'description' => '15.6-inch gaming laptop with AMD Ryzen 7 CPU, NVIDIA GeForce RTX 3070 GPU, and 165Hz refresh rate display.',
                'price' => 1699.99,
                'in_stock' => 1,
                'quantity' => 14,
                'cart_quantity' => 0,
                'category' => 'Laptops & PCs',
                'rating' => 4.8,
                'created_at' => now()->subDays(6),
                'updated_at' => now()->subDay(),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/17014/17014659.png',
                    'title' => 'Lenovo Legion 5 Pro Gaming Laptop',
                    'description' => 'Lenovo Legion 5 Pro Gaming Laptop front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Lenovo Legion 5 Pro Gaming Laptop front view',
                ]
            ],
            [
                'name' => 'Razer DeathAdder V2 Gaming Mouse',
                'description' => 'Ergonomic gaming mouse with Razer Optical Mouse Switches and 20K DPI Focus+ Optical Sensor.',
                'price' => 69.99,
                'in_stock' => 1,
                'quantity' => 20,
                'cart_quantity' => 0,
                'category' => 'Peripherals',
                'rating' => 4.7,
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDay(),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/1537/1537589.png',
                    'title' => 'Razer DeathAdder V2 Gaming Mouse',
                    'description' => 'Razer DeathAdder V2 Gaming Mouse front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Razer DeathAdder V2 Gaming Mouse front view',
                ]
            ],
            [
                'name' => 'ASUS TUF Gaming X570-Plus ATX Motherboard',
                'description' => 'ATX motherboard with AMD X570 chipset, TUF Gaming Alliance design, and support for PCIe 4.0.',
                'price' => 189.99,
                'in_stock' => 1,
                'quantity' => 18,
                'cart_quantity' => 0,
                'category' => 'Motherboards',
                'rating' => 4.6,
                'created_at' => now()->subDays(4),
                'updated_at' => now()->subDays(1),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/5921/5921800.png',
                    'title' => 'ASUS TUF Gaming X570-Plus ATX Motherboard',
                    'description' => 'ASUS TUF Gaming X570-Plus ATX Motherboard top view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'ASUS TUF Gaming X570-Plus ATX Motherboard top view',
                ]
            ],
            [
                'name' => 'Corsair 4000D Airflow ATX Mid Tower Case',
                'description' => 'High airflow ATX Mid Tower case with RapidRoute cable management and tempered glass side panel.',
                'price' => 99.99,
                'in_stock' => 1,
                'quantity' => 16,
                'cart_quantity' => 0,
                'category' => 'Computer Cases',
                'rating' => 4.7,
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subDay(),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/11152/11152835.png',
                    'title' => 'Corsair 4000D Airflow ATX Mid Tower Case',
                    'description' => 'Corsair 4000D Airflow ATX Mid Tower Case front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Corsair 4000D Airflow ATX Mid Tower Case front view',
                ]
            ],
            [
                'name' => 'Motorola Edge 30 Ultra',
                'description' => 'High-end Motorola smartphone with 6.7" OLED display, Snapdragon 8 Gen 1 chipset, and 60MP triple-camera system.',
                'price' => 899.00,
                'in_stock' => 1,
                'quantity' => 19,
                'cart_quantity' => 0,
                'category' => 'Phones & Tablets',
                'rating' => 4.7,
                'created_at' => now()->subDays(90),
                'updated_at' => now()->subDays(85),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/4477/4477610.png',
                    'title' => 'Motorola Edge 30 Ultra',
                    'description' => 'Motorola Edge 30 Ultra front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'Motorola Edge 30 Ultra front view',
                ]
            ],
            [
                'name' => 'MSI GeForce GTX 1650 Super Gaming X',
                'description' => 'Mid-range graphics card with NVIDIA GeForce GTX 1650 Super chipset and TORX Fan 3.0 for quiet and efficient cooling.',
                'price' => 249.99,
                'in_stock' => 1,
                'quantity' => 20,
                'cart_quantity' => 0,
                'category' => 'GPUs',
                'rating' => 4.5,
                'created_at' => now()->subDays(10),
                'updated_at' => now()->subDays(5),
                'image' => [
                    'src' => 'https://cdn-icons-png.flaticon.com/512/11152/11152748.png',
                    'title' => 'MSI GeForce GTX 1650 Super Gaming X',
                    'description' => 'MSI GeForce GTX 1650 Super Gaming X front view',
                    'mime_type' => 'image/png',
                    'alt_text' => 'MSI GeForce GTX 1650 Super Gaming X front view',
                ]
            ],
        ];

        foreach ($products as $productData) {
            $productId = DB::table('products')->insertGetId([
                'name' => $productData['name'],
                'description' => $productData['description'],
                'price' => $productData['price'],
                'in_stock' => $productData['in_stock'],
                'quantity' => $productData['quantity'],
                'cart_quantity' => $productData['cart_quantity'],
                'category' => $productData['category'],
                'rating' => $productData['rating'],
                'created_at' => $productData['created_at'],
                'updated_at' => $productData['updated_at'],
            ]);

            $productImage = new ProductImage();
            $productImage->src = $productData['image']['src'];
            $productImage->title = $productData['image']['title'];
            $productImage->description = $productData['image']['description'];
            $productImage->mime_type = $productData['image']['mime_type'];
            $productImage->alt_text = $productData['image']['alt_text'];

            Product::find($productId)->productImage()->save($productImage);
        }
    }
}